name: build-test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rosdistro:
          - humble

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Sed clone url
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          sed -i -e "s;false;true;" ./.github/Dockerfile.humble
          sed -i -e "s;pull/ID/head;"$(echo "${GITHUB_REF#refs/heads/}" | sed -e "s;refs/;;")";" ./.github/Dockerfile.humble
      
      - name: Docker Build Test
        run: docker build -f ./.github/Dockerfile.humble .
        shell: bash